#! /bin/sh
#reference: Mastering Linux Programming Ch.10 Adding a new Daemon

case "$1" in
    start)
       	echo "Starting aesdsocket"
	start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
	;;
    stop)
	echo "Stopping aesdsocket"
	start-stop-daemon -K -n aesdsocket
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1

esac

exit 0
